version: "3.8"

networks:
  levelZero:
    name: levelZero

services:
  server:
    image: golang:alpine3.18
    working_dir: /bin/cmd/app
    env_file:
      - .env
    volumes:
      - .:/bin
    command: go run main.go
    ports:
      -  ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
      - nats-streaming
    networks:
      - levelZero
  
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_BASE}
      POSTGRES_SSL_MODE: ${PG_SSL_MODE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - levelZero

  nats-streaming:
    image: nats-streaming
    ports:
      - ${NATS_PORT}:${NATS_PORT}
      - 8222:8222
    command:
      - "-cid"
      - ${NATS_CLUSTER_ID}
    networks:
      - levelZero
  
  publisher-test:
      image: golang:alpine3.18
      working_dir: /bin/pkg/publisher
      volumes:
      - .:/bin
      command: go run main.go
      depends_on:
      - server
      networks:
      - levelZero
